vim.keymap.set("n", "<C-d>n", function()
	vim.cmd(":PrtChatToggle")
end)
vim.keymap.set("n", "<C-d>d", function()
	vim.cmd(":PrtChatResponde")
end)
vim.keymap.set("n", "<C-d>h", function()
	vim.cmd(":PrtChatDelete")
end)
vim.keymap.set("v", "<C-d>", function()
	vim.cmd(":'<,'>PrtChatPaste")
end)
