local parrot_leader = "<C-t>"
vim.keymap.set("n", string.format("%sn", parrot_leader), function()
	vim.cmd(":PrtChatToggle")
end)
vim.keymap.set("n", string.format("%sd", parrot_leader), function()
	vim.cmd(":PrtChatResponde")
end)
vim.keymap.set("n", string.format("%sd", parrot_leader), function()
	vim.cmd(":PrtChatDelete")
end)
vim.keymap.set("v", string.format("%s", parrot_leader), function()
	vim.cmd(":'<,'>PrtChatPaste")
end)
